# Config file for automatic testing at travis-ci.org
sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6.0"
  - "3.6"

before_install:
  - if [ "${TRAVIS_PYTHON_VERSION}" = "3.2" ] ; then pip install --no-use-wheel coverage==3.7.1 ; fi
  - if [ "${TRAVIS_PYTHON_VERSION}" != "3.2" ] ; then pip install coverage ; fi

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
cache: pip

after_success:
  - if [ "${TRAVIS_PYTHON_VERSION}" = "3.2" ] ; then coverage run --omit="/home/travis/virtualenv/*" --branch setup.py test ; fi
  - if [ "${TRAVIS_PYTHON_VERSION}" != "3.2" ] ; then coverage run --include="lib/astunparse/*","tests/*","setup.py" --branch setup.py test ; fi
  - coverage report --show-missing
  - bash <(curl -s https://codecov.io/bash)
